spring:
  application:
    name: credit
  datasource:
    url: jdbc:postgresql://localhost:5432/credit
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    admin:
      fail-fast: false
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    consumer:
      bootstrap-servers: kafka-consumer:9092
      group-id: credit-group
      topics:
        new-credits: new-credits
        credits: credits
      dlq-topic: credits-dlq
    producer:
      bootstrap-servers: kafka-producer:9094
      topics:
        credits: credits
        new-credits: new-credits

server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never